# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-09-27 17:47-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: modules/Cmd/add_network/add_network.py:35
msgid "¡La clave pública del servidor no existe!"
msgstr ""

#: modules/Cmd/add_network/add_network.py:39
msgid "¡La clave pública o privada del usuario no existe!"
msgstr ""

#: modules/Cmd/add_network/add_network.py:59
#, python-format
msgid "La dirección '%s' no es válida: %s"
msgstr ""

#: modules/Cmd/add_network/add_network.py:91
#, python-format
msgid "Hubo un error conectado a %s:%d: %s"
msgstr ""

#: modules/Cmd/add_network/add_network.py:99
msgid "Obteniendo servicios..."
msgstr ""

#: modules/Cmd/add_network/add_network.py:119
#, python-format
msgid "La red '%s' no existe, pero se agregará..."
msgstr ""

#: modules/Cmd/add_network/add_network.py:131
#, python-format
msgid ""
"¡No se pudo obtener el identificador de la red '%s' en la base de datos!"
msgstr ""

#: modules/Cmd/add_network/add_network.py:143
#, python-format
msgid "El servicio '%s' ya existe de manera local. No se agregará."
msgstr ""

#: modules/Cmd/add_network/add_network.py:151
#, python-format
msgid ""
"El servicio '%s' no se agregará o actualizará porque está en la lista de "
"exclusión"
msgstr ""

#: modules/Cmd/add_network/add_network.py:158
#, python-format
msgid ""
"No se incluirá el servicio %s porque sólo se prefieren algunos servicios y "
"éste no está incluido ahí"
msgstr ""

#: modules/Cmd/add_network/add_network.py:168
#, python-format
msgid "Agregando servicio '%s' de la red '%s'"
msgstr ""

#: modules/Cmd/add_network/add_network.py:180
#, python-format
msgid "'%s' ya está registrado en la red '%s'"
msgstr ""

#: modules/Cmd/add_network/add_network.py:185
#, python-format
msgid "Ocurrió un error con la petición: %s"
msgstr ""

#: modules/Cmd/add_network/add_network.py:189
#, python-format
msgid "Hubo un error interpretando los datos: %s"
msgstr ""

#: modules/Cmd/add_network/add_network.py:192
#, python-format
msgid "Posible error: %s"
msgstr ""

#: modules/Cmd/add_network/add_network.py:197
#, python-format
msgid "Copiando '%s' a '%s'..."
msgstr ""

#: modules/Cmd/add_network/add_network.py:204
msgid "Hecho."
msgstr ""
